import RequestMap, { type MapPriority, type MapRequest } from "@/components/RequestMap";
import { Button } from "@/components/ui/button";
import { BRICS_COUNTRIES, categoryLabel } from "@/lib/civic";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowUpRight, BrainCircuit, ChevronRight, Globe2, MapPinned, Scale, ShieldCheck, Sparkles, Sprout, UsersRound } from "lucide-react";
import { Link } from "wouter";

import { DEMO_PRIORITIES, DEMO_REQUESTS } from "@/lib/demoData";

export default function Home() {
  const dashboard = trpc.civic.publicDashboard.useQuery(undefined, {
    retry: false,
    refetchOnWindowFocus: false,
  });
  const { user } = useAuth();
  const requests = (dashboard.data?.requests?.length ? dashboard.data.requests : DEMO_REQUESTS) as MapRequest[];
  const priorities = (dashboard.data?.priorities?.length ? dashboard.data.priorities : DEMO_PRIORITIES) as MapPriority[];
  const countryCount = new Set(requests.map(request => request.country)).size;
  return <div className="min-h-screen overflow-x-hidden bg-white text-black"><header className="sticky top-0 z-50 border-b border-black bg-white"><div className="page-grid flex h-16 items-center justify-between"><Link href="/" className="brand-mark">CIVIC<span>NEXUS</span></Link><nav className="hidden items-center gap-6 text-xs font-bold uppercase tracking-[.14em] md:flex"><a href="#how-it-works">How it works</a><a href="#signal-map">Signal map</a><Link href="/policy">Policy workspace</Link></nav><Link href="/submit"><Button className="rounded-none bg-red-700 text-xs uppercase tracking-[.12em] hover:bg-red-800">Submit a signal <ChevronRight /></Button></Link></div></header>
    <main><section className="page-grid grid min-h-[650px] items-end gap-10 border-b border-black py-14 lg:grid-cols-[1.25fr_.75fr] lg:py-20"><div><p className="section-kicker">BRICS civic intelligence / Digital Public Good</p><h1 className="mt-4 max-w-5xl text-5xl font-bold leading-[.88] tracking-[-.075em] sm:text-7xl lg:text-[5.8rem]">From the street-level signal to the policy table.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-neutral-700">CivicNexus turns multilingual citizen requests into structured, privacy-aware evidence that helps BRICS decision-makers locate infrastructure gaps, recognise cross-border patterns, and act with an auditable human review trail.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/submit"><Button className="rounded-none bg-red-700 px-6 hover:bg-red-800"><MapPinned /> Report an infrastructure gap</Button></Link><Link href="/farmer"><Button className="rounded-none bg-emerald-700 px-6 hover:bg-emerald-800"><Sprout /> Farmer advisory</Button></Link><Link href="/policy"><Button variant="outline" className="rounded-none border-black px-6"><BrainCircuit /> Explore policy signals</Button></Link></div></div><div className="relative border border-black bg-black p-6 text-white"><div className="absolute -top-4 -right-4 h-14 w-14 bg-red-700" /><p className="section-kicker !text-red-300">The public-interest promise</p><p className="mt-5 text-2xl font-bold leading-tight tracking-[-.04em]">AI proposes. People verify. Institutions decide.</p><div className="mt-9 grid grid-cols-2 gap-px bg-neutral-700">{[["6", "working languages"], ["5", "BRICS contexts"], ["4", "policy states"], ["0", "hidden scoring rules"]].map(([number, label]) => <div key={label} className="bg-black p-4"><strong className="text-3xl text-red-400">{number}</strong><span className="mt-1 block text-xs text-neutral-300">{label}</span></div>)}</div></div></section>
      <section id="how-it-works" className="page-grid border-b border-black py-16"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker">A complete accountable flow</p><h2 className="mt-3 text-4xl font-bold leading-none tracking-[-.06em]">Structured for participation. Designed for deployment.</h2></div><div className="grid gap-px bg-black sm:grid-cols-3">{[["01", "Collect", "A citizen pins an issue, selects urgency, and writes in a familiar language."], ["02", "Analyse", "Google Gemini classifies, translates, groups overlaps, and explains confidence."], ["03", "Act", "Policymakers rank evidence, create a brief, and advance a visible status pipeline."]].map(([number, title, copy]) => <article key={number} className="bg-white p-6"><p className="text-3xl font-bold text-red-700">{number}</p><h3 className="mt-9 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{copy}</p></article>)}</div></div></section>
      <section id="signal-map" className="page-grid py-16"><div className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="section-kicker">Live public layer / privacy-minimised</p><h2 className="mt-2 text-4xl font-bold tracking-[-.06em]">Where demand concentrates</h2><p className="mt-2 max-w-xl text-xs leading-5 text-neutral-500">Hotspot halos show citizen-signal concentration and urgency, then scale with matching attributable national-context records when they are available.</p></div><div className="flex gap-6 text-sm"><span><strong>{requests.length}</strong> signals</span><span><strong>{countryCount}</strong> countries represented</span><span><strong>{priorities.length}</strong> priorities</span></div></div><RequestMap requests={requests} priorities={priorities} showHeatmap showCorridors /><div className="grid border-x border-b border-black sm:grid-cols-3">{[[Globe2, "Cross-border by default", "Country context is explicit, not assumed."], [Scale, "Traceable prioritisation", "Scores combine urgency, reach, alignment, and model confidence."], [ShieldCheck, "Human rights guardrails", "Public visibility is minimised; review remains human-led."]].map(([Icon, title, copy]) => { const Component = Icon as typeof Globe2; return <div key={String(title)} className="border-r border-black p-5 last:border-r-0"><Component className="h-5 w-5 text-red-700" /><h3 className="mt-5 font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">{String(copy)}</p></div> })}</div></section>
      <section className="border-y border-black bg-neutral-100"><div className="page-grid grid gap-8 py-14 lg:grid-cols-[1fr_1fr]"><div><p className="section-kicker">Decision system, not a black box</p><h2 className="mt-3 text-4xl font-bold tracking-[-.06em]">Evidence that can be challenged, improved, and acted on.</h2></div><div className="grid grid-cols-2 gap-4 text-sm"><div className="border-t-2 border-black pt-3"><Sparkles className="h-5 w-5 text-red-700" /><p className="mt-3 font-bold">Meaningful Google AI</p><p className="mt-1 leading-6 text-neutral-600">Structured Gemini analysis, multilingual translation, duplicate grouping, and brief drafting.</p></div><div className="border-t-2 border-black pt-3"><UsersRound className="h-5 w-5 text-red-700" /><p className="mt-3 font-bold">Role-based operations</p><p className="mt-1 leading-6 text-neutral-600">Citizens submit; policymakers decide; administrators moderate and audit.</p></div></div></div></section>
      <section className="page-grid py-16"><div className="flex flex-wrap items-end justify-between gap-8 border-b border-black pb-8"><div><p className="section-kicker">Ready to make a signal count?</p><h2 className="mt-2 max-w-2xl text-4xl font-bold tracking-[-.06em]">Build a shared evidence base for the infrastructure people need.</h2></div><Link href={user?.role === "admin" ? "/admin" : user?.role === "policymaker" ? "/policy" : "/submit"}><Button className="rounded-none bg-red-700 px-6 hover:bg-red-800">{user?.role === "admin" ? "Open moderation" : user?.role === "policymaker" ? "Open policy board" : "Submit your signal"} <ArrowUpRight /></Button></Link></div><p className="mt-5 max-w-3xl text-xs leading-5 text-neutral-500">Prototype data can be contextualised with publicly available development indicators. CivicNexus is designed to support pilots, not to replace statutory consultation, verification, procurement, or public accountability processes.</p></section>
    </main><footer className="border-t border-black bg-black text-white"><div className="page-grid flex flex-wrap items-center justify-between gap-5 py-6 text-xs"><span className="font-bold tracking-[.14em]">CIVICNEXUS BRICS / 2026</span><span className="text-neutral-400">Multilingual civic evidence for resilient infrastructure</span></div></footer>
  </div>;
}
