import DashboardLayout from "@/components/DashboardLayout";
import RequestMap, { type MapPriority, type MapRequest } from "@/components/RequestMap";
import { Button } from "@/components/ui/button";
import { BRICS_COUNTRIES, LANGUAGES, STATUS_META, categoryLabel, countryName } from "@/lib/civic";
import { exportBriefPdf } from "@/lib/briefPdf";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { BarChart3, BrainCircuit, ChevronRight, Download, FileText, Loader2, Map as MapIcon, ShieldAlert, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type Priority = MapPriority & { category: string; requestCount: number; impactScore: number; alignmentScore: number; contextScore: number; contextEvidence: string[] | null; status: keyof typeof STATUS_META; evidenceBrief: string; aiRationale: string };
type Brief = { id: number; title: string; content: string; createdAt: Date };
type BriefTranslation = { language: (typeof LANGUAGES)[number]["code"]; title: string | null; content: string };

export default function PolicyDashboard() {
  const { user, loading } = useAuth();
  const canAccess = user?.role === "policymaker" || user?.role === "admin";
  const [country, setCountry] = useState<string>("");
  const [selectedPriority, setSelectedPriority] = useState<number | null>(null);
  const [currentBrief, setCurrentBrief] = useState<Brief | null>(null);
  const [briefLanguage, setBriefLanguage] = useState<(typeof LANGUAGES)[number]["code"]>("en");
  const dashboard = trpc.civic.policy.dashboard.useQuery(undefined, { enabled: canAccess });
  const briefs = trpc.civic.policy.briefs.useQuery(undefined, { enabled: canAccess });
  const briefDetail = trpc.civic.policy.briefById.useQuery({ briefId: currentBrief?.id ?? 1 }, { enabled: Boolean(canAccess && currentBrief) });
  const generate = trpc.civic.policy.generateBrief.useMutation({ onSuccess: brief => { setCurrentBrief(brief); briefs.refetch(); toast.success("Evidence brief created immediately and ready for export."); }, onError: error => toast.error(error.message) });
  const refine = trpc.civic.policy.refineBrief.useMutation({ onSuccess: brief => { if (brief) setCurrentBrief(brief); briefDetail.refetch(); briefs.refetch(); toast.success("AI refinement and six-language translations are ready."); }, onError: error => toast.error(error.message) });
  const updateStatus = trpc.civic.policy.updatePriorityStatus.useMutation({ onSuccess: () => { dashboard.refetch(); toast.success("Policy pipeline status updated."); }, onError: error => toast.error(error.message) });
  const priorities = (dashboard.data?.priorities ?? []) as Priority[];
  const requests = (dashboard.data?.requests ?? []) as MapRequest[];
  const selected = priorities.find(item => item.id === selectedPriority) ?? priorities[0];
  const filteredPriorities = useMemo(() => priorities.filter(priority => !country || (priority.countries as string[]).includes(country)), [priorities, country]);
  const selectedTranslation = ((briefDetail.data?.translations ?? []) as BriefTranslation[]).find(item => item.language === briefLanguage);
  const displayedBrief = currentBrief ? { ...currentBrief, title: selectedTranslation?.title ?? currentBrief.title, content: selectedTranslation?.content ?? currentBrief.content } : null;

  if (!loading && !canAccess) return <DashboardLayout><div className="grid min-h-[70vh] place-items-center border border-black bg-white p-8"><div className="max-w-xl text-center"><ShieldAlert className="mx-auto h-10 w-10 text-red-700" /><h1 className="mt-5 text-3xl font-bold tracking-[-.05em]">Policymaker workspace</h1><p className="mt-3 text-neutral-600">This decision-support workspace is restricted to accounts assigned the policymaker or administrator role. An administrator can assign access after your first sign-in.</p></div></div></DashboardLayout>;

  return <DashboardLayout><div className="min-h-screen bg-white text-black">
    <div className="mb-8 flex flex-wrap items-end justify-between gap-5 border-b border-black pb-6"><div><p className="section-kicker">Decision support / live signal layer</p><h1 className="mt-2 text-4xl font-bold tracking-[-.06em]">Policy prioritisation board</h1></div><div className="flex items-center gap-2"><select value={country} onChange={event => setCountry(event.target.value)} className="field-control !w-auto !py-2 text-xs"><option value="">All BRICS countries</option>{BRICS_COUNTRIES.map(item => <option key={item.code} value={item.code}>{item.name}</option>)}</select><span className="border border-black px-3 py-2 text-xs font-bold">{priorities.length} ACTIVE PROGRAMMES</span></div></div>
    <div className="grid gap-5 md:grid-cols-3"><div className="metric-card"><BarChart3 /><p>Ranked priorities</p><strong>{priorities.length}</strong><span>AI-scored; human approval required</span></div><div className="metric-card"><MapIcon /><p>Citizen signals</p><strong>{requests.length}</strong><span>Privacy-minimised geospatial layer</span></div><div className="metric-card"><BrainCircuit /><p>Briefs ready</p><strong>{briefs.data?.length ?? 0}</strong><span>Owner alert on readiness</span></div></div>
    <section className="mt-8 grid gap-8 xl:grid-cols-[1.12fr_.88fr]"><div><div className="mb-3 flex items-center justify-between"><div><p className="section-kicker">Geospatial evidence</p><h2 className="text-xl font-bold">Cross-border signal map</h2><p className="mt-1 text-xs text-neutral-500">Halo scale combines citizen urgency with the matching, attributable national-context score. Click a signal to inspect the contribution.</p></div><div className="map-legend"><span><i className="legend-dot" /> request</span><span><i className="legend-line" /> corridor</span></div></div><RequestMap requests={requests.filter(request => !country || request.country === country)} priorities={filteredPriorities} showHeatmap showCorridors /></div>
      <aside className="border border-black"><div className="bg-black p-5 text-white"><p className="section-kicker !text-red-300">Recommended next action</p><h2 className="mt-2 text-2xl font-bold tracking-[-.04em]">{selected?.title ?? "No policy signals yet"}</h2></div>{selected ? <div className="p-5"><div className="grid grid-cols-2 gap-2 text-center">{[["Impact", selected.impactScore], ["Alignment", selected.alignmentScore], ["National context", selected.contextScore], ["Priority", selected.priorityScore]].map(([label, value]) => <div key={String(label)} className="border border-black p-3"><strong className="block text-2xl">{value}</strong><span className="text-[10px] font-bold uppercase tracking-wider">{label}</span></div>)}</div><p className="mt-5 text-sm leading-6 text-neutral-700">{selected.evidenceBrief}</p><div className="mt-5 border-l-2 border-red-700 pl-3 text-xs leading-5"><strong>Cross-border rationale</strong><br />{selected.aiRationale}</div>{selected.contextEvidence?.length ? <div className="mt-5 border-t border-black pt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-red-700">Attributable national context</p><ul className="mt-2 space-y-1 text-xs leading-5 text-neutral-600">{selected.contextEvidence.map(item => <li key={item}>• {item}</li>)}</ul></div> : <p className="mt-5 text-xs leading-5 text-neutral-500">No national-context records are attached yet. An administrator can synchronise indicators or add an attributed plan record.</p>}<div className="mt-6 flex flex-wrap gap-2">{(selected.countries as string[]).map(code => <span key={code} className="border border-black px-2 py-1 text-[10px] font-bold">{countryName(code)}</span>)}</div><Button onClick={() => generate.mutate({ priorityId: selected.id })} disabled={generate.isPending} className="mt-6 w-full rounded-none bg-red-700 hover:bg-red-800">{generate.isPending ? <Loader2 className="animate-spin" /> : <FileText />} Create instant evidence brief</Button><p className="mt-3 text-center text-[11px] leading-4 text-neutral-500">Creates and exports immediately. AI refinement and six-language translations are optional afterward.</p></div> : <p className="p-5 text-sm text-neutral-500">Submit a citizen signal to begin the transparent prioritisation workflow.</p>}</aside></section>
    <section className="mt-10 grid gap-8 lg:grid-cols-[1fr_.9fr]"><div><div className="mb-4 flex items-end justify-between border-b border-black pb-3"><div><p className="section-kicker">Ranked infrastructure priorities</p><h2 className="text-2xl font-bold tracking-[-.04em]">Evidence before escalation</h2></div><span className="text-xs text-neutral-500">Status advances only forward</span></div><div className="divide-y divide-black border-y border-black">{filteredPriorities.map((priority, index) => { const next = ["submitted", "reviewed", "prioritized", "actioned"][Math.min(3, ["submitted", "reviewed", "prioritized", "actioned"].indexOf(priority.status) + 1)] as keyof typeof STATUS_META; return <button key={priority.id} onClick={() => setSelectedPriority(priority.id)} className={`grid w-full grid-cols-[34px_1fr_auto] gap-3 p-4 text-left transition-colors hover:bg-red-50 ${selected?.id === priority.id ? "bg-neutral-100" : ""}`}><strong className="text-red-700">0{index + 1}</strong><div><h3 className="font-bold">{priority.title}</h3><p className="mt-1 text-xs text-neutral-600">{categoryLabel(priority.category)} · {priority.requestCount} clustered signals · {(priority.countries as string[]).join(" / ")}</p></div><div className="flex flex-col items-end gap-2"><span className={`status-badge ${STATUS_META[priority.status].tone}`}>{STATUS_META[priority.status].label}</span><span className="text-xl font-bold">{priority.priorityScore}</span>{next !== priority.status ? <span onClick={event => { event.stopPropagation(); updateStatus.mutate({ priorityId: priority.id, status: next }); }} className="text-[10px] font-bold uppercase tracking-wider text-red-700 hover:underline">Advance <ChevronRight className="inline h-3 w-3" /></span> : null}</div></button>})}</div></div>
      <div><div className="mb-4 flex items-end justify-between border-b border-black pb-3"><div><p className="section-kicker">Instant evidence briefs</p><h2 className="text-2xl font-bold tracking-[-.04em]">Ready for human review</h2></div>{currentBrief ? <select value={briefLanguage} onChange={event => setBriefLanguage(event.target.value as typeof briefLanguage)} className="field-control !w-auto !py-2 text-xs"><option value="en">English</option><option value="hi">हिन्दी</option><option value="ru">Русский</option><option value="zh">中文</option><option value="pt">Português</option><option value="ar">العربية</option></select> : null}</div><div className="space-y-3">{displayedBrief ? <article className="border-2 border-red-700 bg-red-50 p-5"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker !text-red-700">Selected brief / {briefLanguage.toUpperCase()}</p><h3 className="mt-1 font-bold">{displayedBrief.title}</h3></div><Button variant="outline" onClick={() => exportBriefPdf(displayedBrief)} className="rounded-none border-black"><Download /> PDF</Button></div><pre className="mt-4 max-h-64 overflow-auto whitespace-pre-wrap font-sans text-sm leading-6 text-neutral-700">{displayedBrief.content}</pre><p className="mt-5 border-t border-red-200 pt-4 text-xs leading-5 text-neutral-600">This instant brief is ready to review and export. The main demo workflow intentionally avoids slow model calls.</p></article> : null}{(briefs.data as Brief[] | undefined)?.map(brief => <article key={brief.id} className="flex items-center justify-between gap-4 border border-black p-4"><button onClick={() => setCurrentBrief(brief)} className="min-w-0 text-left"><p className="font-bold">{brief.title}</p><p className="mt-1 text-xs text-neutral-500">Ready for review · {new Date(brief.createdAt).toLocaleDateString()}</p></button><Button variant="outline" onClick={() => { setCurrentBrief(brief); exportBriefPdf(brief); }} className="rounded-none border-black"><FileText /> Export</Button></article>) ?? <p className="border border-dashed border-black p-5 text-sm text-neutral-500">Instant evidence briefs appear here with immediate PDF export.</p>}</div></div></section>
  </div></DashboardLayout>;
}
